Class {
	#name : 'WDMBSPIntersectionOperation',
	#superclass : 'WDMBSPCombinerOperation',
	#instVars : [
		'operands'
	],
	#category : 'WodenModeling-BSPStyleCSG',
	#package : 'WodenModeling-BSPStyleCSG'
}

{ #category : 'as yet unclassified' }
WDMBSPIntersectionOperation >> operands [
	^ operands
]

{ #category : 'as yet unclassified' }
WDMBSPIntersectionOperation >> operands: aListOfOperands [
	^ aListOfOperands
]
